---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-recommender
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
      - name: recommender
        image: registry.k8s.io/autoscaling/vpa-recommender:mine
        args: 
          - "--cpu-histogram-decay-half-life=2m"
          - "--confidence-interval-cpu=2m"
          - "--memory-histogram-decay-half-life=2m"
          - "--confidence-interval-memory=2m"
          - "--recommender-interval=10s"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - name: prometheus
          containerPort: 8942
